/**
 * Transmission Tab - Tab 2
 * Handles differential ratio and gearbox configuration
 */

import { getCurrentCar, updateCurrentCar } from '../carModel.js';
import {
    calculateEngineRpm, msToKmh, kmhToMs,
    calculateWheelTorque, calculateTractiveForce, interpolateTorque
} from '../physics.js';
import { saveToJsonFile, loadFromJsonFile, validateTransmissionData } from '../fileUtils.js';

/**
 * Render the transmission tab
 * @param {HTMLElement} container - Container element
 */
export function renderTransmissionTab(container) {
    const car = getCurrentCar();
    
    container.innerHTML = `
        <div class="card">
            <h2>Gearbox Configuration</h2>
            <div class="form-group" style="max-width: 200px;">
                <label for="gearCount">Number of Gears</label>
                <select id="gearCount">
                    ${[4, 5, 6, 7, 8].map(n =>
                        `<option value="${n}" ${n === car.gearbox.ratios.length ? 'selected' : ''}>${n}-speed</option>`
                    ).join('')}
                </select>
            </div>
        </div>

        <div class="card">
            <h2>Gear Ratios</h2>
            <p style="color: var(--text-muted); margin-bottom: 15px;">
                Enter gear ratios as either m:n format (e.g., 3.82:1) or decimal value (e.g., 3.82).
                Each gear can have its own final drive ratio, or use the same as the previous gear.
            </p>
            <table class="data-table" id="gearRatiosTable">
                <thead>
                    <tr>
                        <th>Gear</th>
                        <th style="min-width: 100px;">Ratio (m:n)</th>
                        <th style="min-width: 80px;">Ratio (dec)</th>
                        <th style="min-width: 80px;">Final Drive</th>
                        <th style="min-width: 60px;">Same as Prev</th>
                        <th>Total Ratio</th>
                        <th>Speed @ 1000 rpm</th>
                    </tr>
                </thead>
                <tbody id="gearRatiosBody">
                    <!-- Rows generated by JavaScript -->
                </tbody>
            </table>
            <div class="table-actions">
                <button class="btn btn-primary" id="applyTransmissionBtn">Apply Changes</button>
            </div>
        </div>

        <div class="card">
            <h2>Gear Speeds</h2>
            <p style="color: var(--text-muted); margin-bottom: 15px;">
                Speed at key engine RPM points for each gear.
            </p>
            <table class="data-table" id="gearSpeedsTable">
                <thead>
                    <tr>
                        <th>Gear</th>
                        <th>Speed @ Peak Torque</th>
                        <th>Speed @ Peak Power</th>
                        <th>Speed @ Optimal Shift</th>
                        <th>Speed @ Redline</th>
                        <th>Speed @ Max Revs</th>
                    </tr>
                </thead>
                <tbody id="gearSpeedsBody">
                    <!-- Rows generated by JavaScript -->
                </tbody>
            </table>
        </div>

        <div class="card">
            <h2>Gear Speed Ranges</h2>
            <p style="color: var(--text-muted); margin-bottom: 15px;">
                This chart shows the speed range for each gear based on engine RPM limits.
            </p>
            <div class="chart-container" style="height: 250px;">
                <canvas id="gearSpeedChart"></canvas>
            </div>
        </div>

        <div class="card">
            <h2>Tractive Force vs Speed</h2>
            <p style="color: var(--text-muted); margin-bottom: 15px;">
                This chart shows the tractive force at the wheels for each gear across the speed range.
                Higher force means better acceleration capability.
            </p>
            <div class="chart-container" style="height: 350px;">
                <canvas id="transmissionTractiveForceChart"></canvas>
            </div>
        </div>

        <div class="card">
            <h2>Save / Load Configuration</h2>
            <p style="color: var(--text-muted); margin-bottom: 15px;">
                Save your transmission settings to a JSON file or load a previously saved configuration.
            </p>
            <div class="table-actions">
                <button class="btn btn-secondary" id="saveTransmissionBtn">💾 Save to JSON</button>
                <button class="btn btn-secondary" id="loadTransmissionBtn">📂 Load from JSON</button>
            </div>
        </div>
    `;

    // Initialize event listeners and populate data
    initializeTransmissionTab();
}

let gearSpeedChart = null;
let tractiveForceChart = null;

/**
 * Initialize the transmission tab
 */
function initializeTransmissionTab() {
    populateGearRatiosTable();
    createGearSpeedChart();
    createTractiveForceChart();
    setupTransmissionEventListeners();
}

/**
 * Find peak torque RPM from engine curve
 * Returns the highest RPM where peak torque occurs (end of flat spot if any)
 * @param {Array} engineCurve - Array of {rpm, torque, power} objects
 * @returns {number} RPM at peak torque
 */
function findPeakTorqueRpm(engineCurve) {
    if (!engineCurve || engineCurve.length === 0) return 3000;

    let peakTorque = 0;
    let peakRpm = engineCurve[0].rpm;

    for (const point of engineCurve) {
        if (point.torque >= peakTorque) {
            peakTorque = point.torque;
            peakRpm = point.rpm;
        }
    }

    return peakRpm;
}

/**
 * Find peak power RPM from engine curve
 * Returns the highest RPM where peak power occurs (end of flat spot if any)
 * @param {Array} engineCurve - Array of {rpm, torque, power} objects
 * @returns {number} RPM at peak power
 */
function findPeakPowerRpm(engineCurve) {
    if (!engineCurve || engineCurve.length === 0) return 5000;

    let peakPower = 0;
    let peakRpm = engineCurve[0].rpm;

    for (const point of engineCurve) {
        if (point.power >= peakPower) {
            peakPower = point.power;
            peakRpm = point.rpm;
        }
    }

    return peakRpm;
}

/**
 * Calculate the optimal shift speed from gear i to gear i+1
 * Returns the minimum speed where tractive force in gear i <= tractive force in gear i+1
 * @param {Object} car - Car object
 * @param {number} gearIndex - Current gear index
 * @returns {number|null} Optimal shift speed in km/h, or null if no crossover exists
 */
function calculateOptimalShiftSpeed(car, gearIndex) {
    const numGears = car.gearbox.ratios.length;

    // Last gear has no next gear to shift to
    if (gearIndex >= numGears - 1) return null;

    const currentTotalRatio = car.getTotalRatio(gearIndex);
    const nextTotalRatio = car.getTotalRatio(gearIndex + 1);

    // Calculate speed ranges for both gears
    const currentMinSpeed = calculateSpeedAtRpm(car.idleRpm, currentTotalRatio, car.wheelRadius);
    const currentMaxSpeed = calculateSpeedAtRpm(car.maxRpm, currentTotalRatio, car.wheelRadius);
    const nextMinSpeed = calculateSpeedAtRpm(car.idleRpm, nextTotalRatio, car.wheelRadius);
    const nextMaxSpeed = calculateSpeedAtRpm(car.maxRpm, nextTotalRatio, car.wheelRadius);

    // The overlap range where both gears can operate
    const overlapMinSpeed = Math.max(currentMinSpeed, nextMinSpeed);
    const overlapMaxSpeed = Math.min(currentMaxSpeed, nextMaxSpeed);

    // No overlap means no valid shift point
    if (overlapMinSpeed >= overlapMaxSpeed) return null;

    // Search for the crossover point within the overlap range
    const numSteps = 100;
    const speedStep = (overlapMaxSpeed - overlapMinSpeed) / numSteps;

    for (let speed = overlapMinSpeed; speed <= overlapMaxSpeed; speed += speedStep) {
        const velocityMs = kmhToMs(speed);

        // Calculate RPM and tractive force for current gear
        const currentRpm = calculateEngineRpm(velocityMs, car.wheelRadius, currentTotalRatio);
        const currentEngineTorque = interpolateTorque(car.engineCurve, currentRpm);
        const currentWheelTorque = calculateWheelTorque(currentEngineTorque, currentTotalRatio, car.drivetrainEfficiency);
        const currentTractiveForce = calculateTractiveForce(currentWheelTorque, car.wheelRadius);

        // Calculate RPM and tractive force for next gear
        const nextRpm = calculateEngineRpm(velocityMs, car.wheelRadius, nextTotalRatio);
        const nextEngineTorque = interpolateTorque(car.engineCurve, nextRpm);
        const nextWheelTorque = calculateWheelTorque(nextEngineTorque, nextTotalRatio, car.drivetrainEfficiency);
        const nextTractiveForce = calculateTractiveForce(nextWheelTorque, car.wheelRadius);

        // Found the crossover point
        if (currentTractiveForce <= nextTractiveForce) {
            return speed;
        }
    }

    // No crossover found - current gear always has more tractive force
    return null;
}

/**
 * Populate the gear ratios table
 */
function populateGearRatiosTable() {
    const car = getCurrentCar();
    const ratiosBody = document.getElementById('gearRatiosBody');

    ratiosBody.innerHTML = car.gearbox.ratios.map((ratio, index) => {
        const finalDrive = car.getFinalDrive(index);
        const totalRatio = ratio * finalDrive;
        const speedAt1000Rpm = calculateSpeedAtRpm(1000, totalRatio, car.wheelRadius);
        const usePrevious = car.gearbox.usePreviousFinalDrive[index] || false;
        const isFirstGear = index === 0;

        return `
            <tr data-index="${index}">
                <td>${car.gearbox.names[index] || `Gear ${index + 1}`}</td>
                <td>
                    <div style="display: flex; gap: 4px; align-items: center;">
                        <input type="text" class="ratio-m-input" data-index="${index}"
                            value="" placeholder="m" style="width: 45px; text-align: center;">
                        <span>:</span>
                        <input type="text" class="ratio-n-input" data-index="${index}"
                            value="" placeholder="n" style="width: 45px; text-align: center;">
                    </div>
                </td>
                <td>
                    <input type="number" class="gear-ratio-input" data-index="${index}"
                        value="${ratio}" step="0.01" min="0.5" max="6.0" style="width: 70px;">
                </td>
                <td>
                    <input type="number" class="final-drive-input" data-index="${index}"
                        value="${car.gearbox.finalDrives[index] || finalDrive}" step="0.01" min="1.0" max="6.0"
                        style="width: 70px;" ${usePrevious && !isFirstGear ? 'disabled' : ''}>
                </td>
                <td style="text-align: center;">
                    ${isFirstGear ? '-' : `
                        <input type="checkbox" class="use-prev-final-drive" data-index="${index}"
                            ${usePrevious ? 'checked' : ''}>
                    `}
                </td>
                <td class="total-ratio-cell">${totalRatio.toFixed(2)}</td>
                <td class="speed-1000rpm-cell">${speedAt1000Rpm.toFixed(1)} km/h</td>
            </tr>
        `;
    }).join('');

    // Populate the gear speeds table
    populateGearSpeedsTable();
}

/**
 * Populate the gear speeds table
 */
function populateGearSpeedsTable() {
    const car = getCurrentCar();
    const speedsBody = document.getElementById('gearSpeedsBody');

    // Find peak torque and power RPMs
    const peakTorqueRpm = findPeakTorqueRpm(car.engineCurve);
    const peakPowerRpm = findPeakPowerRpm(car.engineCurve);

    speedsBody.innerHTML = car.gearbox.ratios.map((ratio, index) => {
        const finalDrive = car.getFinalDrive(index);
        const totalRatio = ratio * finalDrive;
        const speedAtPeakTorque = calculateSpeedAtRpm(peakTorqueRpm, totalRatio, car.wheelRadius);
        const speedAtPeakPower = calculateSpeedAtRpm(peakPowerRpm, totalRatio, car.wheelRadius);
        const optimalShiftSpeed = calculateOptimalShiftSpeed(car, index);
        const speedAtRedline = calculateSpeedAtRpm(car.redlineRpm, totalRatio, car.wheelRadius);
        const speedAtMaxRevs = calculateSpeedAtRpm(car.maxRpm, totalRatio, car.wheelRadius);

        return `
            <tr>
                <td>${car.gearbox.names[index] || `Gear ${index + 1}`}</td>
                <td>${speedAtPeakTorque.toFixed(1)} km/h</td>
                <td>${speedAtPeakPower.toFixed(1)} km/h</td>
                <td>${optimalShiftSpeed !== null ? optimalShiftSpeed.toFixed(1) + ' km/h' : 'N/A'}</td>
                <td>${speedAtRedline.toFixed(1)} km/h</td>
                <td>${speedAtMaxRevs.toFixed(1)} km/h</td>
            </tr>
        `;
    }).join('');
}

/**
 * Calculate speed at given RPM
 * @param {number} rpm - Engine RPM
 * @param {number} totalRatio - Total gear ratio
 * @param {number} wheelRadius - Wheel radius in meters
 * @returns {number} Speed in km/h
 */
function calculateSpeedAtRpm(rpm, totalRatio, wheelRadius) {
    const angularVelocity = rpm * (2 * Math.PI / 60);
    const wheelAngularVelocity = angularVelocity / totalRatio;
    const speedMs = wheelAngularVelocity * wheelRadius;
    return msToKmh(speedMs);
}

/**
 * Create the gear speed range chart
 */
function createGearSpeedChart() {
    const car = getCurrentCar();
    const ctx = document.getElementById('gearSpeedChart')?.getContext('2d');

    if (!ctx) return;

    if (gearSpeedChart) {
        gearSpeedChart.destroy();
    }

    const colors = ['#ef4444', '#f59e0b', '#22c55e', '#3b82f6', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];

    const datasets = car.gearbox.ratios.map((_, index) => {
        const totalRatio = car.getTotalRatio(index);
        const minSpeed = calculateSpeedAtRpm(car.idleRpm, totalRatio, car.wheelRadius);
        const maxSpeed = calculateSpeedAtRpm(car.maxRpm, totalRatio, car.wheelRadius);

        return {
            label: car.gearbox.names[index] || `Gear ${index + 1}`,
            data: [[minSpeed, maxSpeed]],
            backgroundColor: colors[index % colors.length],
            barPercentage: 0.8
        };
    });

    gearSpeedChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Speed Range'],
            datasets: datasets
        },
        options: {
            indexAxis: 'y',
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Speed (km/h)'
                    },
                    min: 0
                }
            },
            plugins: {
                legend: {
                    position: 'top'
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const data = context.raw;
                            return `${context.dataset.label}: ${data[0].toFixed(1)} - ${data[1].toFixed(1)} km/h`;
                        }
                    }
                }
            }
        }
    });
}

/**
 * Create the tractive force vs speed chart
 */
function createTractiveForceChart() {
    const car = getCurrentCar();
    const ctx = document.getElementById('transmissionTractiveForceChart')?.getContext('2d');

    if (!ctx) return;

    if (tractiveForceChart) {
        tractiveForceChart.destroy();
    }

    const colors = ['#ef4444', '#f59e0b', '#22c55e', '#3b82f6', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];
    const numPointsPerGear = 30;

    // Generate data for each gear across its full speed range (idle to max revs)
    const datasets = car.gearbox.ratios.map((_, gearIndex) => {
        const totalRatio = car.getTotalRatio(gearIndex);
        const minSpeed = calculateSpeedAtRpm(car.idleRpm, totalRatio, car.wheelRadius);
        const maxSpeed = calculateSpeedAtRpm(car.maxRpm, totalRatio, car.wheelRadius);
        const speedStep = 1; //(maxSpeed - minSpeed) / numPointsPerGear;

        const dataPoints = [];

        // Add first point at exactly minSpeed
        const minVelocityMs = kmhToMs(minSpeed);
        const minRpm = car.idleRpm;
        const minEngineTorque = interpolateTorque(car.engineCurve, minRpm);
        const minWheelTorque = calculateWheelTorque(minEngineTorque, totalRatio, car.drivetrainEfficiency);
        const minTractiveForce = calculateTractiveForce(minWheelTorque, car.wheelRadius);

        dataPoints.push({
            x: minSpeed,
            y: minTractiveForce,
            rpm: minRpm
        });

        // Loop up to (but not including) maxSpeed
        for (let speed = Math.floor(minSpeed) + 1; speed < maxSpeed; speed += speedStep) {
            const velocityMs = kmhToMs(speed);
            const rpm = calculateEngineRpm(velocityMs, car.wheelRadius, totalRatio);

            // Get engine torque at this RPM
            const engineTorque = interpolateTorque(car.engineCurve, rpm);

            // Calculate wheel torque and tractive force
            const wheelTorque = calculateWheelTorque(engineTorque, totalRatio, car.drivetrainEfficiency);
            const tractiveForce = calculateTractiveForce(wheelTorque, car.wheelRadius);

            dataPoints.push({
                x: speed,
                y: tractiveForce,
                rpm: rpm
            });
        }

        // Add final point at exactly maxSpeed to ensure full RPM range coverage
        const maxVelocityMs = kmhToMs(maxSpeed);
        const maxRpm = car.maxRpm;
        const maxEngineTorque = interpolateTorque(car.engineCurve, maxRpm);
        const maxWheelTorque = calculateWheelTorque(maxEngineTorque, totalRatio, car.drivetrainEfficiency);
        const maxTractiveForce = calculateTractiveForce(maxWheelTorque, car.wheelRadius);

        dataPoints.push({
            x: maxSpeed,
            y: maxTractiveForce,
            rpm: maxRpm
        });

        return {
            label: car.gearbox.names[gearIndex] || `Gear ${gearIndex + 1}`,
            data: dataPoints,
            borderColor: colors[gearIndex % colors.length],
            backgroundColor: colors[gearIndex % colors.length] + '20',
            fill: false,
            tension: 0.3,
            pointRadius: 0,
            borderWidth: 2
        };
    });

    tractiveForceChart = new Chart(ctx, {
        type: 'line',
        data: { datasets },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: {
                mode: 'nearest',
                axis: 'x',
                intersect: false
            },
            scales: {
                x: {
                    type: 'linear',
                    title: {
                        display: true,
                        text: 'Speed (km/h)'
                    },
                    min: 0
                },
                y: {
                    title: {
                        display: true,
                        text: 'Tractive Force (N)'
                    },
                    min: 0
                }
            },
            plugins: {
                legend: {
                    position: 'top'
                },
                tooltip: {
                    callbacks: {
                        title: function(tooltipItems) {
                            if (tooltipItems.length > 0) {
                                return `Speed: ${tooltipItems[0].parsed.x.toFixed(1)} km/h`;
                            }
                            return '';
                        },
                        label: function(context) {
                            const dataPoint = context.dataset.data[context.dataIndex];
                            return `${context.dataset.label}: ${context.parsed.y.toFixed(0)} N @ ${dataPoint.rpm.toFixed(0)} RPM`;
                        }
                    }
                }
            }
        }
    });
}

/**
 * Setup event listeners for the transmission tab
 */
function setupTransmissionEventListeners() {
    // Gear count change
    document.getElementById('gearCount')?.addEventListener('change', (e) => {
        const newCount = parseInt(e.target.value);
        updateGearCount(newCount);
    });

    // Apply button
    document.getElementById('applyTransmissionBtn')?.addEventListener('click', applyTransmissionChanges);

    // m:n ratio inputs - update decimal when m or n changes
    document.querySelectorAll('.ratio-m-input, .ratio-n-input').forEach(input => {
        input.addEventListener('input', handleMNRatioChange);
    });

    // Decimal ratio input - clear m:n when decimal is entered
    document.querySelectorAll('.gear-ratio-input').forEach(input => {
        input.addEventListener('input', handleDecimalRatioChange);
        input.addEventListener('change', updateGearRatiosDisplay);
    });

    // Final drive inputs - need to cascade to dependent gears
    document.querySelectorAll('.final-drive-input').forEach(input => {
        input.addEventListener('change', updateAllFinalDrivesAndTotals);
    });

    // "Same as previous" checkboxes
    document.querySelectorAll('.use-prev-final-drive').forEach(checkbox => {
        checkbox.addEventListener('change', handleUsePreviousFinalDriveChange);
    });

    // Save/Load buttons
    document.getElementById('saveTransmissionBtn')?.addEventListener('click', saveTransmissionToFile);
    document.getElementById('loadTransmissionBtn')?.addEventListener('click', loadTransmissionFromFile);
}

/**
 * Handle m:n ratio input change
 */
function handleMNRatioChange(e) {
    const index = parseInt(e.target.dataset.index);
    const row = e.target.closest('tr');
    const mInput = row.querySelector('.ratio-m-input');
    const nInput = row.querySelector('.ratio-n-input');
    const decimalInput = row.querySelector('.gear-ratio-input');

    const m = parseFloat(mInput.value);
    const n = parseFloat(nInput.value);

    if (!isNaN(m) && !isNaN(n) && n !== 0) {
        const ratio = m / n;
        decimalInput.value = ratio.toFixed(3);
        updateGearRatiosDisplay();
    }
}

/**
 * Handle decimal ratio input change - clear m:n values
 */
function handleDecimalRatioChange(e) {
    const row = e.target.closest('tr');
    const mInput = row.querySelector('.ratio-m-input');
    const nInput = row.querySelector('.ratio-n-input');

    // Clear m:n inputs when user types in decimal
    mInput.value = '';
    nInput.value = '';
}

/**
 * Handle "use previous final drive" checkbox change
 */
function handleUsePreviousFinalDriveChange(e) {
    const index = parseInt(e.target.dataset.index);
    const row = e.target.closest('tr');
    const finalDriveInput = row.querySelector('.final-drive-input');

    if (e.target.checked) {
        // Disable input and show previous gear's final drive
        finalDriveInput.disabled = true;
        const prevFinalDrive = getEffectiveFinalDrive(index - 1);
        finalDriveInput.value = prevFinalDrive.toFixed(2);
    } else {
        // Enable input
        finalDriveInput.disabled = false;
    }

    // Update all rows from this index onwards (cascade effect)
    updateAllFinalDrivesAndTotals();
}

/**
 * Update all final drive displays and total ratios for all gears
 */
function updateAllFinalDrivesAndTotals() {
    const car = getCurrentCar();
    const rows = document.querySelectorAll('#gearRatiosBody tr');

    rows.forEach((row, index) => {
        const finalDriveInput = row.querySelector('.final-drive-input');
        const usePrevCheckbox = row.querySelector('.use-prev-final-drive');
        const ratioInput = row.querySelector('.gear-ratio-input');
        const totalRatioCell = row.querySelector('.total-ratio-cell');
        const speedCell = row.querySelector('.speed-cell');

        if (!ratioInput || !finalDriveInput) return;

        const ratio = parseFloat(ratioInput.value) || car.gearbox.ratios[index];
        const finalDrive = getEffectiveFinalDrive(index);
        const totalRatio = ratio * finalDrive;
        const speedAtRedline = calculateSpeedAtRpm(car.redlineRpm, totalRatio, car.wheelRadius);

        // Update final drive display if using previous
        if (usePrevCheckbox && usePrevCheckbox.checked) {
            finalDriveInput.value = finalDrive.toFixed(2);
        }

        // Update total ratio and speed
        if (totalRatioCell) totalRatioCell.textContent = totalRatio.toFixed(2);
        if (speedCell) speedCell.textContent = speedAtRedline.toFixed(1) + ' km/h';
    });
}

/**
 * Sync table inputs to car gearbox data
 */
function syncTableToGearbox() {
    const car = getCurrentCar();

    // Sync gear ratios from table inputs
    document.querySelectorAll('.gear-ratio-input').forEach(input => {
        const index = parseInt(input.dataset.index);
        if (index < car.gearbox.ratios.length) {
            car.gearbox.ratios[index] = parseFloat(input.value) || car.gearbox.ratios[index];
        }
    });

    // Sync final drives and use previous flags
    document.querySelectorAll('.final-drive-input').forEach(input => {
        const index = parseInt(input.dataset.index);
        if (index < car.gearbox.finalDrives.length) {
            car.gearbox.finalDrives[index] = parseFloat(input.value) || car.gearbox.finalDrives[index];
        }
    });

    document.querySelectorAll('.use-prev-final-drive').forEach(checkbox => {
        const index = parseInt(checkbox.dataset.index);
        if (index < car.gearbox.usePreviousFinalDrive.length) {
            car.gearbox.usePreviousFinalDrive[index] = checkbox.checked;
        }
    });

    // Update legacy differentialRatio to first gear's final drive
    car.differentialRatio = car.gearbox.finalDrives[0] || car.differentialRatio;
}

/**
 * Update gear count
 * @param {number} newCount - New number of gears
 */
function updateGearCount(newCount) {
    // First sync any edits from the table
    syncTableToGearbox();

    const car = getCurrentCar();
    const currentCount = car.gearbox.ratios.length;

    if (newCount > currentCount) {
        // Add gears with decreasing ratios
        for (let i = currentCount; i < newCount; i++) {
            const lastRatio = car.gearbox.ratios[car.gearbox.ratios.length - 1];
            const lastFinalDrive = car.gearbox.finalDrives[car.gearbox.finalDrives.length - 1];
            car.gearbox.ratios.push(Math.max(0.5, lastRatio * 0.8));
            car.gearbox.names.push(`${i + 1}${getOrdinalSuffix(i + 1)}`);
            car.gearbox.finalDrives.push(lastFinalDrive);
            car.gearbox.usePreviousFinalDrive.push(true);
        }
    } else if (newCount < currentCount) {
        // Remove gears
        car.gearbox.ratios = car.gearbox.ratios.slice(0, newCount);
        car.gearbox.names = car.gearbox.names.slice(0, newCount);
        car.gearbox.finalDrives = car.gearbox.finalDrives.slice(0, newCount);
        car.gearbox.usePreviousFinalDrive = car.gearbox.usePreviousFinalDrive.slice(0, newCount);
    }

    populateGearRatiosTable();
    createGearSpeedChart();
    createTractiveForceChart();
    setupTransmissionEventListeners();
}

/**
 * Get ordinal suffix (st, nd, rd, th)
 * @param {number} n - Number
 * @returns {string} Ordinal suffix
 */
function getOrdinalSuffix(n) {
    const s = ["th", "st", "nd", "rd"];
    const v = n % 100;
    return s[(v - 20) % 10] || s[v] || s[0];
}

/**
 * Get effective final drive for a gear index based on table inputs
 * Traces back through the chain of "same as previous" to find the source value
 * @param {number} index - Gear index
 * @returns {number} Final drive ratio
 */
function getEffectiveFinalDrive(index) {
    // Find the source gear - the first one in the chain without "same as previous" checked
    let sourceIndex = index;

    while (sourceIndex > 0) {
        const row = document.querySelector(`tr[data-index="${sourceIndex}"]`);
        if (!row) break;

        const usePrevCheckbox = row.querySelector('.use-prev-final-drive');
        if (!usePrevCheckbox || !usePrevCheckbox.checked) {
            break; // This gear has its own final drive value
        }
        sourceIndex--;
    }

    // Get the value from the source gear
    const sourceRow = document.querySelector(`tr[data-index="${sourceIndex}"]`);
    if (!sourceRow) return 3.73;

    const finalDriveInput = sourceRow.querySelector('.final-drive-input');
    return parseFloat(finalDriveInput?.value) || 3.73;
}

/**
 * Update gear ratios display after input change
 */
function updateGearRatiosDisplay() {
    // Use the unified update function that handles all cases
    updateAllFinalDrivesAndTotals();
}

/**
 * Apply transmission changes
 */
function applyTransmissionChanges() {
    // Sync all table inputs to car gearbox
    syncTableToGearbox();

    const car = getCurrentCar();

    // Refresh display
    populateGearRatiosTable();
    createGearSpeedChart();
    createTractiveForceChart();
    setupTransmissionEventListeners();

    alert('Transmission settings updated successfully!');
}

/**
 * Save transmission data to JSON file
 */
function saveTransmissionToFile() {
    // First sync the table to car
    syncTableToGearbox();

    const car = getCurrentCar();
    const numGears = car.gearbox.ratios.length;

    const transmissionData = {
        gearbox: {
            ratios: [...car.gearbox.ratios],
            names: car.gearbox.names.slice(0, numGears),
            finalDrives: [...car.gearbox.finalDrives],
            usePreviousFinalDrive: [...car.gearbox.usePreviousFinalDrive]
        },
        // Legacy support
        differentialRatio: car.gearbox.finalDrives[0] || car.differentialRatio
    };

    // Generate filename
    const filename = `transmission_${numGears}speed`;

    saveToJsonFile(transmissionData, filename);
}

/**
 * Load transmission data from JSON file
 */
function loadTransmissionFromFile() {
    loadFromJsonFile((data) => {
        // Validate the data
        const validation = validateTransmissionData(data);

        if (!validation.valid) {
            alert(`Invalid transmission file:\n${validation.errors.join('\n')}`);
            return;
        }

        // Update the car with new transmission data
        const car = getCurrentCar();
        const numGears = data.gearbox.ratios.length;
        const defaultFinalDrive = data.differentialRatio || 3.73;

        car.gearbox = {
            ratios: [...data.gearbox.ratios],
            names: data.gearbox.names || data.gearbox.ratios.map((_, i) => `${i + 1}${getOrdinalSuffix(i + 1)}`),
            finalDrives: data.gearbox.finalDrives || new Array(numGears).fill(defaultFinalDrive),
            usePreviousFinalDrive: data.gearbox.usePreviousFinalDrive || [false, ...new Array(numGears - 1).fill(true)]
        };

        // Update legacy differential ratio
        car.differentialRatio = car.gearbox.finalDrives[0] || defaultFinalDrive;

        // Re-render the tab to show new values
        const container = document.getElementById('transmission');
        if (container) {
            renderTransmissionTab(container);
        }

        alert(`Transmission loaded: ${numGears}-speed gearbox`);
    });
}
